- name: Stop containerd service
  ansible.builtin.systemd:
    name: "{{ docker_containerd_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: Stop docker service
  ansible.builtin.systemd:
    name: "{{ docker_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true

- name: Remove docker data directory and configuration file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_config_path }}"
    - "{{ docker_data_path }}"
    - "{{ docker_log_path }}"
    - "{{ docker_unix_sock_file }}"
    - "{{ docker_pid_file }}"
    - "{{ docker_exec_root_path }}"
    - "{{ docker_containerd_config_path }}"
    - "{{ docker_containerd_root_path }}"
    - "{{ docker_containerd_state_path }}"
    - "{{ docker_containerd_socket_file }}"
    - "{{ docker_containerd_opt_path }}"

- name: Remove docker binary files
  ansible.builtin.file:
    path: "{{ (docker_install_path, item) | path_join }}"
    state: absent
  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v2
    - ctr
    - docker
    - dockerd
    - docker-init
    - docker-proxy
    - runc
